---
- become: 'yes'
  gather_facts: 'no'
  hosts: dbserver
  name: Run app npm build
  tasks:
    - command: npm --version
      ignore_errors: 'yes'
      name: Check if npm is installed
      register: npm_check
      #add chonky
    - name: Install npm if not found
      package:
        name: npm
        state: present
      when: npm_check.rc != 0
    - command: chdir=/home/{{ ansible_user }}/src/ioliz/fileManger npm i
      name: Install fileManger project dependencies
    - command: chdir=/home/{{ ansible_user }}/src/ioliz/fileManger npm run link-pub
      name: link fileManger project dependencies
    - command: chdir=/home/{{ ansible_user }}/src/ioliz/app npm i
      name: Install project dependencies
    - command: chdir=/home/{{ ansible_user }}/src/ioliz/app npm link chonky
      name: build app
    - command: chdir=/home/{{ ansible_user }}/src/ioliz/app npm run build
      become_user: root
      name: deploy
    - copy:
        dest: /home/{{ ansible_user }}/www/app
        remote_src: 'yes'
        src: /home/{{ ansible_user }}/src/ioliz/app/build/ # build/:只copy build子目录， 不带/只会copy build目录过去