---
- name: Run app npm build
  hosts: dbserver
  gather_facts: no
  become: yes  # This allows you to become a superuser if necessary
  tasks:
    - name: Check if npm is installed
      command: npm --version
      register: npm_check
      ignore_errors: yes

    - name: Install npm if not found
      package:
        name: npm
        state: present
      when: npm_check.rc != 0

   - name: Install fileManager project dependencies
      command: chdir=/home/{{ ansible_user }}/src/ioliz/fileManager npm install 
   - name: build fileManager project dependencies
      command: chdir=/home/{{ ansible_user }}/src/ioliz/fileManager npm run build
   - name: link fileManager project dependencies
      command: chdir=/home/{{ ansible_user }}/src/ioliz/fileManager npm link

    - name: Install project dependencies
      command: chdir=/home/{{ ansible_user }}/src/ioliz/app npm install --force
      #add chonky
    - name: Install chonky 
      command: chdir=/home/{{ ansible_user }}/src/ioliz/app npm install link chonky

    - name: build
      command:  chdir=/home/{{ ansible_user }}/src/ioliz/app npm run build
      
    - name: Copy the directory
      copy:
        src: /home/{{ ansible_user }}/src/ioliz/app/build/*  # Replace with the path to your local directory
        dest: /home/{{ ansible_user }}/www/app  # Replace with the path on the remote host
        remote_src: yes
        recurse: yes