---
- become: 'yes'
  gather_facts: 'no'
  hosts: dbserver
  name: Run app npm build
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
    - name: Check if nodejs is installed
      command: nodejs --version
      ignore_errors: 'yes'
      register: nodejscheck
      
    - name: Install or update nodejs to the latest version
      command: sh '/home/{{ ansible_user }}/src/ioliz/automate/install_nodejs.sh'
      become_user: root
      when: nodejscheck.rc != 0

    - name: Verify npm is installed
      command: npm --version
      register: npm_version
      ignore_errors: yes  # Ignore errors in case npm is not installed

    - name: Print npm version
      debug:
        var: npm_version.stdout

    - name: fileManager npm i
      command: chdir=/home/{{ ansible_user }}/src/ioliz/fileManger npm install --force
    - name: Install fileManger project dependencies
      command: chdir=/home/{{ ansible_user }}/src/ioliz/fileManger npm run link-pub

    - name: link fileManger project dependencies
      command: chdir=/home/{{ ansible_user }}/src/ioliz/app npm install --force
    - name: Install project dependencies
      command: chdir=/home/{{ ansible_user }}/src/ioliz/app npm link chonky

    - name: build app
      command: chdir=/home/{{ ansible_user }}/src/ioliz/app npm run build

    - name: deploy
      copy:
        dest: /home/{{ ansible_user }}/www/app
        remote_src: 'yes'
        src: /home/{{ ansible_user }}/src/ioliz/app/build/ # build/:只copy build子目录， 不带/只会copy build目录过去