---
- name: Build Docker service, run ../webhook-setup/deploy_dev.sh
  hosts: docker_hosts
  gather_facts: no
  tasks:
    - name: Build Docker service
      command: sh '/home/{{ ansible_user }}/src/ioliz/webhook-setup/deploy_dev.sh'
      become: yes
      become_user: root