---
- name: Clone ioliz Repository
  hosts: dbserver
  gather_facts: no
  tasks:
    - name: Clone Git Repository
      ansible.builtin.git:
        repo: https://github.com/cnboker/ioliz.git
        dest: ~/src/ioliz
        version: HEAD  # Optionally, specify a branch or tag
        #update: yes     # Optionally, specify a branch or tag
        force: true  # Reset the destination to match the remote repository
    # Additional tasks can be added here if needed
