---
- name: Install MySQL in Docker on Raspberry Pi
  hosts: dbserver
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Get infos on container
      docker_container_info:
        name: mysql
      register: result
    - name: Run MySQL Docker container
      docker_container:
        name: mysql
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ROO#2012
        volumes:
          - /home/ubuntu/data/mysql:/var/lib/mysql
        networks:
          - name: myNetwork
        ports:
          - "3306:3306"
        state: started
        restart_policy: always
      when: not result.exists