version: "3.3"
services:
  server:
    restart: always
    build:
      #设置父目录为根目录，只有这样才能将service和shared目录文件copy到docker conatiner
      #service项目依赖shared项目
      context: ../
      #指定Dockerfile文件位置
      dockerfile: ./service/Dockerfile
    ports:
    #HOST:CONTAINER
      - "6001:6001"
    networks:
      - "myNetwork"
    external_links:
      - ":mysql"
networks:
  myNetwork:
    external: true