// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Config {
    userName : string;
    deviceId : string;
    FileServer : string;
    MQTTServer:string;
    token : string;
}

export interface Device {
    deviceId : string;
    name : string;
    os : string;
    resolution? : string;
    mac : string;
    ip : string;
    status : number;
    lastUpdateTime : string;
    tenantUserName : string;
    authorizeStatus : number;
    authorizeCode : string;
    authorizeDate : string;
}
