export const CONTENT_READY_EVENT = 'CONTENT_READY_EVENT'
// export const DOWNLAOD_COMPLETE_EVENT = 'DOWNLAOD_COMPLETE_EVENT'
// export const SINGLE_FILE_DOWNLOAD_COMPLETE_EVENT = 'SingleFileDownloadComplete'
export const SNAPSHOT_EVENT = 'SNAPSHOT_EVENT'