// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface License {
    userName : string;
    deviceId : string;
    resourceServer : string;
    token : string;
}

export interface Device {
    deviceId : string;
    name : string;
    os : string;
    resolution : null;
    mac : string;
    ip : string;
    status : number;
    lastUpdateTime : string;
    tenantUserName : string;
    authorizeStatus : number;
    authorizeCode : string;
    authorizeDate : string;
    currentLicenseId : number;
    sensorCode : null;
}
