#docker run --restart=always --network host -d -v /etc/frp/frpc.ini:/etc/frp/frpc.ini --name frpc snowdreamtech/frpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-dsliz-info
  namespace: default
  labels:
    app: www-dsliz-info
spec:
  selector:
    matchLabels:
      app: www-dsliz-info
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: www-dsliz-info
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi

          ports:
            - containerPort: 8000
              protocol: TCP
              name: http-svc
          volumeMounts:
            - name: homedir
              mountPath: /usr/share/nginx/html/
      volumes:
        - name: homedir
          hostPath:
            path: /www-dsliz-info
            type: DirectoryOrCreate
      restartPolicy: Always
      #hostNetwork: true
---
apiVersion: v1
kind: Service
metadata:
  name: www-dsliz-info
  namespace: default
spec:
  selector:
    app: www-dsliz-info
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      #targetPort: http-svc
      # If you set the `spec.type` field to `NodePort` and you want a specific port number,
      # you can specify a value in the `spec.ports[*].nodePort` field.
      #nodePort:
