version: '3.3'
services:
  mosquitto:
    restart: always
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "8000:8000"
    volumes:
      - /home/mosquitto/data:/mosquitto/data
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /home/mosquitto/log:/mosquitto/log
