version: '3.3'

services:
   reverseproxy:
     container_name: reverseproxy
     image: nginx
     restart: always
     ports:
      - "80"
     networks:
       - "myNetwork"
networks:
  myNetwork:
    external: true