version: '3.3'

services:
    reverseproxy:
        build: .
        ports:
        #[host:container]
            - "80:80"
        volumes:
            - /home/www:/release/wwwroot
        networks:
            - "myNetwork"
        restart: always

    authapi:
        depends_on:
            - reverseproxy
        image: member_server:latest
        restart: always
        networks:
            - "myNetwork"
        ports:
            - "7800:7800"
    serviceapi:
        depends_on:
            - reverseproxy
        image: service_server:latest
        restart: always
        networks:
            - "myNetwork"
        ports:
            - "6001:6001"
    fileapi:
        depends_on:
            - reverseproxy
        image: fileserver_server:latest
        restart: always
        networks:
            - "myNetwork"
        volumes:
            #host:container
            - /home/data/files:/release/wwwroot
        ports:
            - "5000:5000"
networks:
  myNetwork:
    external: true