version: '3.3'

services:
    reverseproxy:
        build: .
        ports:
            #[host:container]
            - "80:80"
        volumes:
        #[host:docker container]
            - /home/ioliz/_www:/www
            - /home/ubuntu/dist/app:/www/app
        networks:
            - "myNetwork"
        restart: always
    jsxbuild:
        depends_on:
            - reverseproxy
        restart: always
        image: jsxbuildserver_server:latest
    ffmpegapi:
        restart: always
        depends_on:
            - reverseproxy
        image: ffmpegserver_server:latest
    authapi:
        depends_on:
            - reverseproxy
        image: member_server:latest
    serviceapi:
        depends_on:
            - reverseproxy
        image: service_server:latest
    fileapi:
        depends_on:
            - reverseproxy
        image: fileserver_server:latest
networks:
    myNetwork:
        external: true
