version: '3.3'

services:
    reverseproxy:
        build: .
        ports:
            - "80"
        networks:
            - "myNetwork"
        restart: always

    authapi:
        depends_on:
            - reverseproxy
        image: member_server
        restart: always

    serviceapi:
        depends_on:
            - reverseproxy
        image: service_server
        restart: always

    fileapi:
        depends_on:
            - reverseproxy
        image: fileserver_server
        restart: always

networks:
  myNetwork:
    external: true