version: "3.3"
services:
  server:
    restart: always
    build:
      #设置父目录为根目录，只有这样才能在Dockerfile文件将member和shared目录文件copy到docker conatiner
      #member项目依赖shared项目
      context: ../
      #指定Dockerfile文件位置
      dockerfile: ./member/Dockerfile
    # depends_on:
    #   - "db"
    # command: ["./wait-for-it.sh"]
    ports:
    #(HOST:CONTAINER),
      - "7800:7800"
    networks:
    # cmd: docker network create myNetwork
      - "myNetwork"
    #增加链接确保数据库连接字符串可以使用mysql名称连接mysql container， 通过这种方法可以解决重新启动mysql服务器ip改变的情况
    external_links:
      - ":mysql"
networks:
  myNetwork:
    external: true

# db:
#   container_name: mysql
#   image: mysql
#   ports:
#       - "3306"
#   environment:
#         MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#         MYSQL_USER: "root"
#         MYSQL_PASSWORD: "1"
#         MYSQL_DATABASE: "mysql"
#   healthcheck:
#         test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#         timeout: 20s
#         retries: 10
