#docker run --restart=always --network host -d -v /etc/frp/frpc.ini:/etc/frp/frpc.ini --name frpc snowdreamtech/frpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  frpc-deploy
  namespace: default
  labels:
    app:  frpc-deploy
spec:
  selector:
    matchLabels:
      app: frpc-deploy
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  frpc-deploy
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  frpc-container
        image:  snowdreamtech/frpc
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort:  8888
          name:  frpc
        volumeMounts:
        - name: frpc-config
          mountPath: /etc/frp/frpc.toml
      volumes:
        - name: frpc-config
          hostPath:
            path: /etc/frp/frpc.toml
      restartPolicy: Always
      hostNetwork: true
---
apiVersion: v1
kind: Service
metadata:
  name: frpc-service
  namespace: default
spec:
  selector:
    app: frpc-deploy
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: frpc-service
    protocol: TCP
    port: 8888
    #targetPort: 
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    #nodePort: 