version: "3.9"
services:
  server:
    build:
      #设置父目录为根目录，只有这样才能在Dockerfile文件将fileServer和shared目录文件copy到docker conatiner
      #fileServer项目依赖shared项目
      context: ../
      #指定Dockerfile文件位置
      dockerfile: ./fileServer/Dockerfile
    ports:
      - "5000:80"
    volumes:
      - /home/scott/code/ioliz/data/files:/usr/share/files:ro