export const CLIENT_SET = "CLIENT_SET"
export const CLIENT_UNSET = "CLIENT_UNSET"
export const RECEIVE_USER_EXTENDER = 'RECEIVE_USER_EXTENDER'
export const UPDATE_USER_EXTENDER ='UPDATE_USER_EXTENDER'
export const RECEIVE_CMS_USER = 'RECEIVE_CMS_USER'