export const DEVICE_AUTHORIZE_RESPONSE = 'DEVICE_AUTHORIZE_RESPONSE'
export const AUTHORIZE_LIST_RESPONSE = 'AUTHORIZE_LIST_RESPONSE'
export const AUTHORIZE_TOKEN_RESPONSE = 'AUTHORIZE_TOKEN_RESPONSE'
